name: dilaundry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  d_button: ^0.0.10
  d_input: ^0.1.3
  d_method: ^0.2.6
  d_view: ^0.0.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/